name: TEST_WID
on:
  workflow_dispatch:
    branches:
      - hacker

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: prod
    name: WIF-GCP-GHA
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - id: auth
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: ${{ secrets.WID_ID_PROVIDER }}
          service_account: ${{ secrets.SA }}
          project_id: ${{ secrets.PROJECT_ID }}
          audience: ${{ secrets.GH_AUDIENCE }}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud secrets versions access latest --secret=my-super-secret'